#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# evilwm directory
DIR="$HOME/.evilwm"

# Launch dunst daemon
if [[ `pidof dunst` ]]; then
	pkill dunst
fi

dunst -config "$DIR"/dunstrc &
